-- Database schema for Aptitude Question Uploader

-- 1. Table for Aptitude Topics
CREATE TABLE IF NOT EXISTS aptitude_topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Table for Aptitude Questions
CREATE TABLE IF NOT EXISTS aptitude_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT REFERENCES aptitude_topics(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    explanation TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Table for Aptitude Options
CREATE TABLE IF NOT EXISTS aptitude_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT REFERENCES aptitude_questions(id) ON DELETE CASCADE,
    option_text TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_aptitude_questions_topic ON aptitude_questions(topic_id);
CREATE INDEX IF NOT EXISTS idx_aptitude_options_question ON aptitude_options(question_id);
